"""
transcribe.py — URL in, transcript out.

Order of operations:
  1. parse video id
  2. fetch metadata (title, channel, duration) — no download
  3. try caption tracks, in priority order, with quality checks
  4. fall back to whisper.cpp on downloaded audio
  5. return a uniform dict either way

Run directly for testing:
    python transcribe.py https://www.youtube.com/watch?v=ksojZseGcrU [--prose]
"""

import json
import logging
import re
import subprocess
import sys
import time
from pathlib import Path

from yt_dlp import YoutubeDL
from youtube_transcript_api import YouTubeTranscriptApi

import settings

# --- tune these ------------------------------------------------------------
#
# The constants marked [setting] are only defaults: the live value comes from
# settings.get() at call time, so the panel and the CLI always agree. Change
# a default here; change the value with settings.set().

MIN_COVERAGE = 0.85      # [setting] captions must reach this fraction of the runtime
MIN_DENSITY = 0.20       # [setting] covered segment time / runtime; below this, suspect
MIN_WORDS_PER_MIN = 20   # [setting] crude sanity check on caption volume

WHISPER_EXE = Path("whisper/whisper-cli.exe")
WHISPER_MODEL = Path("models/ggml-medium-q5_0.bin")     # [setting] whisper_model
WHISPER_THREADS = 8                                     # [setting]
WHISPER_LANGUAGE = "auto"    # [setting] language: whisper's -l; "auto" or a code like "ru"
WHISPER_BEAM = 1         # -bs; 1 = greedy
WHISPER_BEST_OF = 1      # -bo

# Token-level probabilities come only from the full JSON output. They are
# what makes LOW_CONF below meaningful, so this is on by default.
WHISPER_FULL_JSON = True
LOW_CONF = 0.60          # mean token probability under this = flag the segment

# Voice activity detection: skips non-speech before encoding. Encode is ~70%
# of runtime here, so on a video with music, gaps or long ad breaks this is
# the one setting that can beat 0.25x without a GPU build. Needs its own
# model: huggingface.co/ggml-org/whisper-vad -> models/ggml-silero-v6.2.0.bin
WHISPER_VAD = False                                     # [setting] vad_enabled
WHISPER_VAD_MODEL = Path("models/ggml-silero-v6.2.0.bin")
WHISPER_VAD_THRESHOLD = None     # [setting] vad_threshold; None = whisper.cpp default

AUDIO_DIR = Path("audio")
KEEP_AUDIO = False       # True while debugging

YTDLP_PROXY = None       # e.g. "socks5://127.0.0.1:1080"
YTDLP_FORMAT = "bestaudio[protocol^=http]"   # avoid fragmented HLS

# ---------------------------------------------------------------------------

log = logging.getLogger("transcribe")


def video_id(url: str) -> str:
    """Pull the 11-char id out of any YouTube URL shape."""
    patterns = [
        r"(?:v=|/v/|youtu\.be/|/embed/|/shorts/|/live/)([0-9A-Za-z_-]{11})",
        r"^([0-9A-Za-z_-]{11})$",   # a bare id
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    raise ValueError(f"no video id in: {url}")


def fetch_metadata(vid: str) -> dict:
    """Title, channel, duration. No media downloaded."""
    opts = {"quiet": True, "no_warnings": True, "skip_download": True}
    if YTDLP_PROXY:
        opts["proxy"] = YTDLP_PROXY
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(f"https://www.youtube.com/watch?v={vid}", download=False)
    return {
        "video_id": vid,
        "title": info.get("title"),
        "channel": info.get("uploader") or info.get("channel"),
        "duration": info.get("duration"),      # seconds
        "language": info.get("language"),      # often None
    }


# --- captions --------------------------------------------------------------

def pick_track(vid: str, original_lang: str | None):
    """
    Preference order:
      1. manual track in the video's own language
      2. auto (ASR) track in the video's own language
      3. nothing — translated tracks are deliberately ignored

    Returns (track, kind) or (None, reason).
    """
    try:
        tracks = list(YouTubeTranscriptApi().list(vid))
    except Exception as e:
        return None, f"no track list ({type(e).__name__})"

    if not tracks:
        return None, "no tracks"

    # Tracks YouTube generated by translating another track carry
    # is_translated; those are a translation of a guess, so skip them.
    native = [t for t in tracks if not getattr(t, "is_translated", False)]
    if not native:
        return None, "only translated tracks"

    # Which language is the video actually in? yt-dlp often doesn't say,
    # so fall back to the language of the non-translated tracks.
    langs = {t.language_code for t in native}
    lang = original_lang if original_lang in langs else None
    if lang is None:
        # prefer a manual track's language, else whatever the ASR track is in
        manual = [t for t in native if not t.is_generated]
        lang = (manual[0] if manual else native[0]).language_code

    for generated, kind in ((False, "manual"), (True, "auto")):
        for t in native:
            if t.language_code == lang and t.is_generated == generated:
                return t, kind

    return None, f"no usable track in {lang}"


def caption_quality(segments: list, duration: int) -> dict:
    """Coverage, density, words/min — the three numbers we log and branch on."""
    if not segments or not duration:
        return {"coverage": 0.0, "density": 0.0, "words_per_min": 0.0}

    last = segments[-1]
    coverage = (last["start"] + last["duration"]) / duration

    # Auto-captions scroll: each line stays on screen while the next
    # appears, so segments overlap and a plain sum double-counts.
    # Merge overlapping intervals to get actual covered time.
    spans = sorted((s["start"], s["start"] + s["duration"]) for s in segments)
    covered, cur_start, cur_end = 0.0, *spans[0]
    for start, end in spans[1:]:
        if start > cur_end:
            covered += cur_end - cur_start
            cur_start, cur_end = start, end
        else:
            cur_end = max(cur_end, end)
    covered += cur_end - cur_start
    density = covered / duration

    words = sum(len(s["text"].split()) for s in segments)
    return {
        "coverage": round(coverage, 3),
        "density": round(density, 3),
        "words_per_min": round(words / (duration / 60), 1),
    }


def try_captions(meta: dict) -> dict:
    """
    Always returns a verdict dict. `accepted` says whether the captions are
    usable; `reasons` says why not. The caller records both either way —
    rejections are how you learn where the thresholds should actually sit.
    """
    vid, duration = meta["video_id"], meta["duration"]

    track, kind = pick_track(vid, meta.get("language"))
    if track is None:
        log.info("captions: %s", kind)
        return {"accepted": False, "track": None, "quality": None, "reasons": [kind]}

    try:
        fetched = track.fetch()
    except Exception as e:
        reason = f"fetch failed ({type(e).__name__})"
        log.info("captions: %s", reason)
        return {"accepted": False, "track": kind, "quality": None, "reasons": [reason]}

    segments = [
        {"start": s.start, "duration": s.duration, "text": s.text}
        for s in fetched
    ]
    q = caption_quality(segments, duration)
    log.info("captions: %s/%s coverage=%.2f density=%.2f wpm=%.0f\n",
             kind, track.language_code, q["coverage"], q["density"], q["words_per_min"])

    s = settings.all()
    min_cov, min_den, min_wpm = s["min_coverage"], s["min_density"], s["min_words_per_min"]
    reasons = []
    if q["coverage"] < min_cov:
        reasons.append(f"coverage {q['coverage']:.2f} < {min_cov}")
    if q["density"] < min_den:
        reasons.append(f"density {q['density']:.2f} < {min_den}")
    if q["words_per_min"] < min_wpm:
        reasons.append(f"wpm {q['words_per_min']:.0f} < {min_wpm}")

    if reasons:
        log.info("captions rejected: %s", "; ".join(reasons))
        return {"accepted": False, "track": kind, "quality": q, "reasons": reasons}

    return {
        "accepted": True,
        "track": kind,
        "quality": q,
        "reasons": [],
        "source": f"captions-{kind}",
        "language": track.language_code,
        "segments": segments,
    }


# --- whisper ---------------------------------------------------------------

def download_audio(vid: str, dest: Path) -> Path:
    """16 kHz mono wav, which is what whisper.cpp wants."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    opts = {
        "format": YTDLP_FORMAT,
        "outtmpl": str(dest.with_suffix(".%(ext)s")),
        "quiet": True,
        "no_warnings": True,
        "retries": 20,
        "socket_timeout": 60,
        "postprocessors": [{
            "key": "FFmpegExtractAudio",
            "preferredcodec": "wav",
        }],
        "postprocessor_args": {"ffmpeg": ["-ar", "16000", "-ac", "1"]},
    }
    if YTDLP_PROXY:
        opts["proxy"] = YTDLP_PROXY
    with YoutubeDL(opts) as ydl:
        ydl.download([f"https://www.youtube.com/watch?v={vid}"])
    return dest.with_suffix(".wav")


_HELP_CACHE = None


def whisper_supports(flag: str) -> bool:
    """
    Flag names drift between whisper.cpp builds, and an unknown one makes the
    whole run fail. Ask the binary once and cache its help text.
    """
    global _HELP_CACHE
    if _HELP_CACHE is None:
        try:
            p = subprocess.run([str(WHISPER_EXE), "-h"], capture_output=True,
                               text=True, encoding="utf-8", errors="replace", timeout=30)
            _HELP_CACHE = (p.stdout or "") + (p.stderr or "")
        except Exception:
            _HELP_CACHE = ""
    return flag in _HELP_CACHE


def _token_probability(tok) -> float | None:
    """Builds name this field differently; take whichever is present."""
    if not isinstance(tok, dict):
        return None
    for key in ("p", "probability", "prob", "confidence"):
        v = tok.get(key)
        if isinstance(v, (int, float)):
            return float(v)
    return None


def segment_confidence(seg: dict) -> float | None:
    """
    Mean token probability for one segment. Returns None when the build did
    not give per-token data, so callers can tell 'no data' from 'low score'.
    """
    tokens = seg.get("tokens") or []
    ps = [p for p in (_token_probability(t) for t in tokens) if p is not None]
    if not ps:
        return None
    return sum(ps) / len(ps)


def transcribe_audio(wav: Path, prompt: str | None = None,
                     on_progress=None) -> dict:
    """
    Run whisper.cpp and parse its JSON.

    This is the seam: to switch to a Vulkan build or a hosted API later,
    replace the body of this function and nothing else changes.

    stderr is read rather than discarded — it carries live progress, the
    language-detection probability and the temperature-fallback count, all
    of which say something about how much to trust the result.
    """
    out_base = wav.with_suffix("")
    json_flag = "-ojf" if (WHISPER_FULL_JSON and whisper_supports("-ojf")) else "-oj"

    # Read once per run, so one transcription can't see a setting half-changed.
    s = settings.all()
    model = Path(s["whisper_model"])
    vad = s["vad_enabled"]

    cmd = [
        str(WHISPER_EXE),
        "-m", str(model),
        "-f", str(wav),
        json_flag,
        "-of", str(out_base),
        "-l", s["language"],
        "-t", str(s["whisper_threads"]),
        "-bs", str(WHISPER_BEAM),
        "-bo", str(WHISPER_BEST_OF),
    ]
    if whisper_supports("--print-progress"):
        cmd.append("--print-progress")
    if prompt:
        # Primes the decoder with expected vocabulary — mainly helps
        # proper nouns, which is where this model visibly slips.
        cmd += ["--prompt", prompt]
    if vad and whisper_supports("--vad"):
        if not WHISPER_VAD_MODEL.exists():
            raise FileNotFoundError(
                f"VAD is on but {WHISPER_VAD_MODEL} is missing. Get it from "
                "huggingface.co/ggml-org/whisper-vad"
            )
        cmd += ["--vad", "-vm", str(WHISPER_VAD_MODEL)]
        if s["vad_threshold"] is not None:
            cmd += ["--vad-threshold", str(s["vad_threshold"])]

    # stdout is the transcript echoed back; we read the json file instead.
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
                            text=True, encoding="utf-8", errors="replace", bufsize=1)

    signals = {"lang_p": None, "fallbacks_p": None, "fallbacks_h": None}
    pct_re = re.compile(r"progress\s*=\s*(\d+)\s*%")
    lang_re = re.compile(r"auto-detected language:\s*(\w+)\s*\(p\s*=\s*([\d.]+)\)")
    fb_re = re.compile(r"fallbacks\s*=\s*(\d+)\s*p\s*/\s*(\d+)\s*h")
    last_pct = -1

    for line in proc.stderr:
        m = pct_re.search(line)
        if m:
            pct = int(m.group(1))
            if pct != last_pct:
                last_pct = pct
                if on_progress:
                    on_progress(pct)
            continue
        m = lang_re.search(line)
        if m:
            signals["lang_p"] = float(m.group(2))
            continue
        m = fb_re.search(line)
        if m:
            signals["fallbacks_p"] = int(m.group(1))
            signals["fallbacks_h"] = int(m.group(2))

    if proc.wait() != 0:
        raise RuntimeError(f"whisper exited {proc.returncode}")

    data = json.loads(out_base.with_suffix(".json").read_text(encoding="utf-8"))

    segments, confs = [], []
    for s in data["transcription"]:
        c = segment_confidence(s)
        if c is not None:
            confs.append(c)
        segments.append({
            "start": s["offsets"]["from"] / 1000,
            "duration": (s["offsets"]["to"] - s["offsets"]["from"]) / 1000,
            "text": s["text"].strip(),
            "confidence": round(c, 3) if c is not None else None,
        })

    mean_conf = round(sum(confs) / len(confs), 3) if confs else None
    low = [s for s in segments
           if s["confidence"] is not None and s["confidence"] < LOW_CONF]

    if mean_conf is not None:
        log.info("whisper: confidence %.2f  low segments %d/%d  lang_p %s  fallbacks %s",
                 mean_conf, len(low), len(segments),
                 signals["lang_p"], signals["fallbacks_p"])
    elif WHISPER_FULL_JSON:
        log.info("whisper: no per-token data in this build's json (flag %s)", json_flag)

    return {
        "source": f"whisper-{model.stem}" + ("-vad" if vad else ""),
        "language": data["result"]["language"],
        "segments": segments,
        "quality": None,
        "confidence": mean_conf,
        "low_conf_count": len(low),
        "lang_p": signals["lang_p"],
        "fallbacks": signals["fallbacks_p"],
    }


# --- entry point -----------------------------------------------------------

def transcribe(url: str, on_progress=None) -> dict:
    """URL -> metadata + transcript. Captions if usable, whisper otherwise."""
    t0 = time.perf_counter()
    timings = {}

    meta = fetch_metadata(video_id(url))
    timings["metadata"] = round(time.perf_counter() - t0, 2)
    log.info("Video: %s (%ss)\nAuthor: %s", meta["title"], meta["duration"], meta["channel"])

    t = time.perf_counter()
    attempt = try_captions(meta)
    timings["captions"] = round(time.perf_counter() - t, 2)

    # Recorded whether or not the captions were used.
    caption_attempt = {
        "track": attempt["track"],
        "quality": attempt["quality"],
        "reasons": attempt["reasons"],
        "accepted": attempt["accepted"],
    }

    if attempt["accepted"]:
        result = attempt
    else:
        t = time.perf_counter()
        wav = download_audio(meta["video_id"], AUDIO_DIR / meta["video_id"])
        timings["download"] = round(time.perf_counter() - t, 2)
        try:
            t = time.perf_counter()
            prompt = " ".join(filter(None, [meta["title"], meta["channel"]]))
            result = transcribe_audio(wav, prompt=prompt, on_progress=on_progress)
            timings["whisper"] = round(time.perf_counter() - t, 2)
        finally:
            if not KEEP_AUDIO:
                wav.unlink(missing_ok=True)

    timings["total"] = round(time.perf_counter() - t0, 2)
    # How long it took relative to the video's own length — the number
    # that says whether this is instant or a coffee break.
    if meta["duration"]:
        timings["realtime_factor"] = round(timings["total"] / meta["duration"], 3)

    return {**meta, **result, "timings": timings, "caption_attempt": caption_attempt}


def as_text(result: dict) -> str:
    """
    Timestamped lines. A segment whisper was unsure of is marked, so both a
    reader and an analysis prompt can see which words not to lean on.
    """
    out = []
    for s in result["segments"]:
        mark = ""
        c = s.get("confidence")
        if c is not None and c < LOW_CONF:
            mark = " ~"
        out.append(f"[{int(s['start'] // 60):02d}:{int(s['start'] % 60):02d}]{mark} {s['text']}")
    return "\n".join(out)


PROSE_PAUSE = 1.2        # seconds of silence between segments that end a paragraph
PROSE_MIN = 15           # a paragraph is at least this long before a pause can end it
PROSE_MAX = 60           # ...and no longer than this: auto-captions overlap, so they
                         # never pause, and would otherwise run on as one block


def as_prose(result: dict) -> str:
    """
    The same segments merged into paragraphs, for reading rather than
    scanning. A paragraph ends on a real pause in the speech (a gap between
    one segment's end and the next one's start), and is capped at PROSE_MAX
    so pause-less caption tracks still break. Each paragraph starts with its
    timestamp; a low-confidence segment keeps its ~ inline, so prose hides
    nothing that as_text() shows.
    """
    paras, cur, start, last_end = [], [], None, None
    for s in result["segments"]:
        text = " ".join(s["text"].split())
        if not text:
            continue
        gap = s["start"] - last_end if last_end is not None else 0
        if cur and ((gap >= PROSE_PAUSE and s["start"] - start >= PROSE_MIN)
                    or s["start"] - start >= PROSE_MAX):
            paras.append((start, cur))
            cur = []
        if not cur:
            start = s["start"]
        c = s.get("confidence")
        cur.append(f"~{text}" if c is not None and c < LOW_CONF else text)
        last_end = s["start"] + s.get("duration", 0)
    if cur:
        paras.append((start, cur))
    return "\n\n".join(
        f"[{int(t // 60):02d}:{int(t % 60):02d}] {' '.join(words)}" for t, words in paras
    )


def summary(result: dict) -> str:
    lines = [
        f"# Video name: {result['title']}",
        f"# Channel name: {result['channel']}",
        f"# source: {result['source']}",
        f"# language: {result['language']}",
    ]
    q = result.get("quality")
    if q:
        lines.append(
            f"# coverage: {q['coverage']:.2f}  density: {q['density']:.2f}"
            f"  wpm: {q['words_per_min']:.0f}"
        )
    if result.get("confidence") is not None:
        lines.append(
            f"# confidence: {result['confidence']:.2f}"
            f"  low segments: {result.get('low_conf_count', 0)}/{len(result['segments'])}"
            + (f"  lang_p: {result['lang_p']:.2f}" if result.get("lang_p") else "")
            + (f"  fallbacks: {result['fallbacks']}" if result.get("fallbacks") is not None else "")
        )
    t = result.get("timings")
    if t:
        stages = "  ".join(f"{k}: {v}s" for k, v in t.items() if k != "realtime_factor")
        lines.append(f"# {stages}")
        if "realtime_factor" in t:
            lines.append(f"# realtime factor: {t['realtime_factor']:.3f}x")
    return "\n".join(lines)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stderr)

    def show(pct):
        print(f"\r  whisper {pct:3d}%", end="", file=sys.stderr, flush=True)

    args = [a for a in sys.argv[1:] if a != "--prose"]
    r = transcribe(args[0], on_progress=show)
    print(file=sys.stderr)
    head = summary(r)
    print(head, end="\n\n")
    print(as_prose(r) if "--prose" in sys.argv else as_text(r), end="\n\n")
    print(head)